const PolishV2 = {
    init() {
        console.log("PolishV2 initializing...");
        this.addAriaLabels();
        this.setupKeyboardHandlers();
        this.setupClickOutside();
        this.fixPortAnimations();
        this.addWatermarkToYaml();
        this.addResetSafetyNet();
        console.log("PolishV2 initialized!");
    },

    addAriaLabels() {
        // Find buttons without labels and add them
        const buttons = document.querySelectorAll('button:not([aria-label])');
        buttons.forEach(btn => {
            if (btn.title) {
                btn.setAttribute('aria-label', btn.title);
            } else if (btn.innerHTML.includes('fa-')) {
                // If it's an icon button, try to guess label from class
                const icon = btn.querySelector('i');
                if (icon) {
                    const cls = Array.from(icon.classList).find(c => c.startsWith('fa-'));
                    if (cls) btn.setAttribute('aria-label', cls.replace('fa-', '').replace('-', ' '));
                }
            }
        });
    },

    setupKeyboardHandlers() {
        document.addEventListener('keydown', (e) => {
            if (e.key === 'Escape') {
                // 1. Close command reference
                const cmdRef = document.getElementById('cmd-ref-panel');
                if (cmdRef) cmdRef.remove();

                // 2. Close preflight
                const preflight = document.getElementById('preflight-overlay');
                if (preflight) preflight.remove();

                // 3. Close step help cards
                document.querySelectorAll('.step-help-card').forEach(el => el.remove());

                // 4. Close template previews
                if (window.TemplatePreviewer) window.TemplatePreviewer.hidePreview();
            }
        });
    },

    setupClickOutside() {
        document.addEventListener('click', (e) => {
            // Click outside Command Reference
            const cmdRef = document.getElementById('cmd-ref-panel');
            const cmdRefBtn = document.querySelector('.cmd-ref-btn');
            if (cmdRef && !cmdRef.contains(e.target) && cmdRefBtn && !cmdRefBtn.contains(e.target)) {
                cmdRef.remove();
            }
        });
    },

    fixPortAnimations() {
        // Add class to graph container when connections exist
        const graph = document.getElementById('graph-container');
        if (!graph) return;

        const updateConnectionsClass = () => {
            const connections = window.AppState.getConnections();
            if (connections.length > 0) {
                graph.classList.add('has-connections');
            } else {
                graph.classList.remove('has-connections');
            }
        };

        // Monitor connections
        const originalAdd = window.AppState.addConnection;
        if (originalAdd) {
            window.AppState.addConnection = function() {
                originalAdd.apply(this, arguments);
                updateConnectionsClass();
            };
        }

        const originalRemove = window.AppState.removeConnection;
        if (originalRemove) {
            window.AppState.removeConnection = function() {
                originalRemove.apply(this, arguments);
                updateConnectionsClass();
            };
        }

        // Add CSS rule dynamically for the port pulse fix
        const style = document.createElement('style');
        style.textContent = `
            body.guided-mode #graph-container:not(.has-connections) .port {
                animation: portPulse 1.5s infinite;
                box-shadow: 0 0 15px var(--accent-color);
            }
        `;
        document.head.appendChild(style);
        
        updateConnectionsClass();
    },

    addWatermarkToYaml() {
        if (window.YamlGenerator && window.YamlGenerator.updateYaml) {
            const originalUpdate = window.YamlGenerator.updateYaml;
            window.YamlGenerator.updateYaml = function() {
                originalUpdate.apply(this, arguments);
                try {
                    const textArea = document.getElementById('yaml-output');
                    if (textArea && textArea.value && !textArea.value.startsWith('# Generated by')) {
                        textArea.value = `# Generated by Karokh's PipelinePro Visual Builder\n` + textArea.value;
                    }
                } catch (e) {
                    console.log('PolishV2 updateYaml error:', e);
                }
            };
        }
    },

    addResetSafetyNet() {
        // Add button to settings modal
        const settingsModal = document.getElementById('settings-modal');
        if (!settingsModal) return;

        const hr = document.createElement('hr');
        hr.style.margin = '20px 0';
        hr.style.opacity = '0.2';
        settingsModal.appendChild(hr);

        const label = document.createElement('div');
        label.className = 'section-label';
        label.textContent = 'Beginner Features (Safety Net)';
        settingsModal.appendChild(label);

        const btn = document.createElement('button');
        btn.className = 'danger';
        btn.style.width = '100%';
        btn.innerHTML = '<i class="fas fa-undo"></i> Reset All Helper Settings';
        btn.onclick = () => {
            if (confirm("This will reset your experience level, onboarding status, and all helper preferences. The page will reload. Proceed?")) {
                Object.keys(localStorage).forEach(key => {
                    if (key.startsWith('pipelinepro_')) localStorage.removeItem(key);
                });
                location.reload();
            }
        };
        settingsModal.appendChild(btn);
    }
};

window.PolishV2 = PolishV2;

document.addEventListener('DOMContentLoaded', () => {
    setTimeout(() => PolishV2.init(), 2300);
});
