const YamlPlayground = {
    editMode: false,

    init() {
        console.log("YamlPlayground initialized");
        this.injectToggle();
    },

    injectToggle() {
        const yamlTab = document.getElementById('tab-yaml');
        if (!yamlTab) return;

        const headerRow = yamlTab.querySelector('div[style*="margin-bottom: 12px"]');
        if (!headerRow) return;

        if (headerRow.querySelector('.playground-toggle-btn')) return;

        const btn = document.createElement('button');
        btn.className = 'secondary playground-toggle-btn';
        btn.style.cssText = 'padding:4px 8px; font-size:12px; margin-left:4px;';
        btn.innerHTML = '<i class="fas fa-pencil-alt"></i> Edit Mode';
        btn.title = 'Edit the YAML directly and see changes on the canvas';
        btn.onclick = () => this.toggleEditMode();

        headerRow.appendChild(btn);
    },

    toggleEditMode() {
        this.editMode = !this.editMode;

        const btn = document.querySelector('.playground-toggle-btn');
        const textArea = document.getElementById('yaml-output');
        if (!textArea) return;

        if (this.editMode) {
            textArea.removeAttribute('readonly');
            textArea.style.border = '2px solid var(--accent-color)';
            textArea.style.background = 'rgba(var(--accent-rgb, 59, 130, 246), 0.03)';
            if (btn) btn.innerHTML = '<i class="fas fa-lock"></i> Lock YAML';

            // Add event listener for changes
            textArea._playgroundHandler = this.debounce(() => {
                this.parseAndApply(textArea.value);
            }, 1500);
            textArea.addEventListener('input', textArea._playgroundHandler);

            // Show instruction banner
            this.showBanner(textArea);

            if (window.showNotification) {
                window.showNotification('YAML Edit Mode enabled. Changes will update the canvas after you stop typing.', 'info');
            }
        } else {
            textArea.setAttribute('readonly', true);
            textArea.style.border = '';
            textArea.style.background = '';
            if (btn) btn.innerHTML = '<i class="fas fa-pencil-alt"></i> Edit Mode';

            if (textArea._playgroundHandler) {
                textArea.removeEventListener('input', textArea._playgroundHandler);
            }

            this.removeBanner();

            // Regenerate YAML from current state to overwrite any bad edits
            if (window.YamlGenerator && window.YamlGenerator.updateYaml) {
                window.YamlGenerator.updateYaml();
            }
        }
    },

    showBanner(textArea) {
        this.removeBanner();
        const banner = document.createElement('div');
        banner.className = 'playground-banner';
        banner.innerHTML = '<i class="fas fa-info-circle"></i> <strong>Edit Mode:</strong> You can type changes directly. The canvas will update when you stop typing. If something breaks, turn off Edit Mode to reset.';
        textArea.parentNode.insertBefore(banner, textArea);
    },

    removeBanner() {
        const existing = document.querySelector('.playground-banner');
        if (existing) existing.remove();
    },

    parseAndApply(yamlText) {
        // Strip the watermark comment line
        const cleanYaml = yamlText.replace(/^# Generated by.*\n?/m, '');

        let parsed;
        try {
            parsed = jsyaml.load(cleanYaml);
        } catch (e) {
            // Show parse error but do not crash
            this.showParseError(e);
            return;
        }

        this.clearParseError();

        if (!parsed) return;

        // Determine platform
        const isGitHub = parsed.on !== undefined;
        const isGitLab = (parsed.stages !== undefined || parsed.workflow !== undefined) && parsed.on === undefined;

        if (isGitHub) {
            this.applyGitHubYaml(parsed);
        } else if (isGitLab) {
            this.applyGitLabYaml(parsed);
        }
    },

    applyGitHubYaml(parsed) {
        if (!parsed.jobs || typeof parsed.jobs !== 'object') return;

        // Update trigger config
        if (parsed.on) {
            const on = parsed.on;
            if (typeof on === 'object') {
                window.AppState.pipeline.triggers.push = !!on.push;
                window.AppState.pipeline.triggers.pr = !!on.pull_request;
                if (on.push && on.push.branches && on.push.branches.length > 0) {
                    window.AppState.pipeline.branch = on.push.branches[0];
                }
            }
        }

        // Update jobs from parsed YAML
        Object.entries(parsed.jobs).forEach(([yamlId, jobDef]) => {
            const existingJob = window.AppState.jobs.find(j => j.yamlId === yamlId);
            if (existingJob) {
                // Update name
                if (jobDef.name) existingJob.name = jobDef.name;
                // Update OS
                if (jobDef['runs-on']) existingJob.os = jobDef['runs-on'];
                // Update steps
                if (jobDef.steps && Array.isArray(jobDef.steps)) {
                    existingJob.steps = jobDef.steps.map(s => {
                        if (s.uses && s.uses.includes('checkout')) {
                            return { type: 'checkout', name: s.name || 'Checkout Code', val: '' };
                        } else if (s.uses) {
                            return { type: 'action', name: s.name || s.uses, val: s.uses };
                        } else if (s.run) {
                            return { type: 'run', name: s.name || 'Run Command', val: s.run };
                        }
                        return { type: 'run', name: s.name || 'Unknown Step', val: '' };
                    });
                }
            }
        });

        // Rebuild UI
        this.rebuildCanvasFromState();
    },

    applyGitLabYaml(parsed) {
        // GitLab CI parsing
        if (parsed.stages && Array.isArray(parsed.stages)) {
            window.AppState.pipeline.stages = parsed.stages;
        }

        Object.entries(parsed).forEach(([key, val]) => {
            if (key === 'stages' || key === 'variables' || key === 'default' || key === 'image' || key === 'workflow') return;
            if (typeof val !== 'object' || val === null) return;

            const existingJob = window.AppState.jobs.find(j => j.yamlId === key);
            if (existingJob) {
                if (val.stage) existingJob.stage = val.stage;
                if (val.image) existingJob.os = val.image;
                if (val.script && Array.isArray(val.script)) {
                    existingJob.steps = val.script.map(cmd => ({
                        type: 'run',
                        name: cmd.substring(0, 30),
                        val: cmd
                    }));
                }
            }
        });

        this.rebuildCanvasFromState();
    },

    rebuildCanvasFromState() {
        // Remove all nodes from canvas
        const container = document.getElementById('graph-container');
        if (!container) return;

        container.querySelectorAll('.node').forEach(n => n.remove());

        // Re-render all jobs
        window.AppState.jobs.forEach(job => {
            if (window.NodeRenderer && window.NodeRenderer.renderNode) {
                window.NodeRenderer.renderNode(job);
            }
        });

        // Re-draw connections
        if (window.ConnectionManager && window.ConnectionManager.drawLines) {
            window.ConnectionManager.drawLines();
        }

        // Update validation
        if (window.Validation && window.Validation.updateValidation) {
            window.Validation.updateValidation();
        }

        // Select previously selected job if it still exists
        if (window.AppState.selectedId) {
            const job = window.AppState.getJob(window.AppState.selectedId);
            if (job && window.JobManager && window.JobManager.selectJob) {
                window.JobManager.selectJob(job.internalId);
            }
        }

        if (window.showNotification) {
            window.showNotification('Canvas updated from YAML changes', 'success');
        }
    },

    showParseError(error) {
        let errorBar = document.querySelector('.playground-parse-error');
        if (!errorBar) {
            errorBar = document.createElement('div');
            errorBar.className = 'playground-parse-error';
            const textArea = document.getElementById('yaml-output');
            if (textArea) textArea.parentNode.insertBefore(errorBar, textArea);
        }
        const lineMatch = error.message.match(/line (\d+)/);
        const lineInfo = lineMatch ? ` on line ${lineMatch[1]}` : '';
        errorBar.innerHTML = `<i class="fas fa-exclamation-triangle"></i> YAML syntax error${lineInfo}: ${error.reason || error.message}`;
    },

    clearParseError() {
        const errorBar = document.querySelector('.playground-parse-error');
        if (errorBar) errorBar.remove();
    },

    debounce(func, wait) {
        let timeout;
        return function() {
            clearTimeout(timeout);
            timeout = setTimeout(func, wait);
        };
    }
};

window.YamlPlayground = YamlPlayground;

document.addEventListener('DOMContentLoaded', () => {
    setTimeout(() => YamlPlayground.init(), 2500);
});
